name: Make executable from python file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        run: sudo apt install python3
      - name: check directory location
        run: pwd
      - name: list files
        run: ls -laGh
      - name: install pip dependencies
        run: pip install -r requirements.txt
      - name: build executable file
        run: pyinstaller --onefile spotify.py
      - name: check generated files
        run: ls -laGh
      - uses: actions/upload-artifact@v2
        with:
          name: Ubuntu-x64
          path: /home/runner/work/spotify/spotify/dist/spotify
  
  Windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: My location (pwd)
        shell: powershell
        run: pwd
      - name: list files
        shell: powershell
        run: ls
      - name: install pip dependencies
        shell: powershell
        run: pip install -r requirements.txt
      - name: build executable file
        run: pyinstaller --onefile spotify.py
      - name: list builded files
        shell: powershell
        run: ls
      - uses: actions/upload-artifact@v2
        with:
          name: Windows-x64
          path: D:\a\spotify\spotify\dist\spotify.exe
          
