name: Make executable from python file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python and c stuff
        run: sudo apt install python3.8 build-essential
      - name: Install cython
        run: pip install Cython
      - name: check directory location
        run: pwd
      - name: list files
        run: ls -laGh
      - name: Compile to c file via Cython
        run: python3 setup.py
      - name: Compile executable file with Cython
        run: gcc -Os -I /usr/include/python3.8 spotify.c -lpython3.8 -o spotify
      - name: check generated files
        run: ls -laGh
      - uses: actions/upload-artifact@v2
        with:
          name: Ubuntu-x64
          path: /home/runner/work/spotify/spotify/spotify
  
  Windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: My location (pwd)
        shell: powershell
        run: pwd
      - name: Install python3
        shell: powershell
        run: choco install -y python3
      - name: Install cython
        shell: powershell
        run: pip install Cython
      - name: Compile to .c file via Cython
        shell: cmd
        run: python3 setup.py
      - name: list files
        shell: powershell
        run: ls
      - name: msbuild helper
        shell: powershell
        run: msbuild /?
      - name: Compile spotify.c
        shell: powershell
        run: msbuild /t:ClCompile /p:SelectedFiles=spotify.c
