name: Make executable from python file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Ubuntu-buils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install necessary packages
        run: sudo apt install python3 cython3 build-essentials
      - name: check directory location
        run: pwd
      - name: list files
        run: ls -laGh
      - name: Compile executable file with Cython
        run: gcc -Os -I /usr/include/python3.10/ spotify.c -lpython3.10 -o spotify
